// Shlok Patel
// 20th March 2023
/* This is a lottery system that asks you how many tickets you would like to generate and stores them in a file of their own.
 * It then conducts a draw by generating a random set of winning numbers and a megaplier.
 * It goes through each ticket and checks how many numbers it has correct and based on that awards the prizes.
 * It calculates the number of winners, total sales, total payout, average amount won per winning ticket & per all tickets and total profit
 * If jackpot is won it generates the cash option or annuity option. */


// Header files
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

// macro definitions
#define NUM_WHITE_BALLS 5
#define MAX_WHITE_BALL 70
#define MAX_GOLD_BALL 25
#define JACKPOT 100000000

// function prototypes
int randNum(int min, int max);
void random_white_balls(int* white_balls);
int random_gold_ball();
int random_megaplier();
void generate_winning_numbers(int* white_balls, int* gold_ball);
void generate_megaplier(int *megaplier);
void check_tickets(int* winning_white_balls, int winning_gold_ball, int megaplier, char* file_name, int numTickets);
void cash_vs_annuity();


int main()
{
    srand(time(NULL));
    signed int numTickets;
    int winning_white_balls[NUM_WHITE_BALLS];
    int winning_gold_ball;
    int megaplier;

    printf("How many tickets do you want to generate? "); // asks the user how many tickets they want to generate
    scanf("%d", &numTickets); // stores in the numtickets variable

    while(numTickets < 0) // ensures that numTickets is positive and keeps asking until it is
    {
        printf("How many tickets do you want to generate? ");
        scanf("%d", &numTickets);
    }

    // Generate and save the tickets to a file
    FILE* lotteryF = fopen("lottery_tickets.txt", "w");
    if(!lotteryF)
    {
        printf("Failed to open file\n");
        return 1;
    }
    for(int i = 1; i <= numTickets; i++)
    {
        // Generate the white numbers for the ticket and stores in white_balls
        int white_balls[NUM_WHITE_BALLS];
        random_white_balls(white_balls);
        // Generates the golf number for the ticket and stores in gold_ball
        int gold_ball = random_gold_ball();
        megaplier = random_megaplier(); // Generates whether the ticket has a megaplier or not i.e 1 or 0
        // Save the ticket to the file
        fprintf(lotteryF, "%d %d %d %d %d %d %d %d\n", i,
                white_balls[0], white_balls[1], white_balls[2], white_balls[3], white_balls[4],
                gold_ball, megaplier);
    }

    // Close the file
    fclose(lotteryF);
    printf("Tickets saved to lottery_tickets.txt\n");
    // Prints how many tickets you have requested
    printf("You have requested %d tickets\n", numTickets);
    // Generate a set of winning numbers
    generate_winning_numbers(winning_white_balls, &winning_gold_ball);
    // Generate a random megaplier between 2 and 5
    generate_megaplier(&megaplier);
    // Checks the tickets for winners and prints the profit loss statistics
    check_tickets(winning_white_balls, winning_gold_ball, megaplier, "lottery_tickets.txt", numTickets);

    return 0;

}

//Generate a random set of 5 distinct white balls
void random_white_balls(int* white_balls)
{
    int used_ball[MAX_WHITE_BALL] = {0}; // an array to keep track of which white balls have been used
    for(int i = 0; i < NUM_WHITE_BALLS; i++) // loop through the five white balls
    {
        int ball;
        do{
            ball = randNum(1, MAX_WHITE_BALL); // generate a random number between 1 and 70 for the white ball
        }while (used_ball[ball - 1]); // keep generating random numbers until an unused number is generated
        used_ball[ball - 1] = 1; // mark the ball as used
        white_balls[i] = ball; // add the ball to the ticket
    }
    // Sort the white balls in ascending order
    for(int i = 0; i < NUM_WHITE_BALLS - 1; i++) // loop through all pairs of white balls
    {
        for(int j = i + 1; j < NUM_WHITE_BALLS; j++)
        {
            if(white_balls[i] > white_balls[j]) // if the current ball is greater than the next ball
            {
                int tmp = white_balls[i]; // swap the current ball with the next ball
                white_balls[i] = white_balls[j];
                white_balls[j] = tmp;
            }
        }
    }
}
//Generate a random gold ball
int random_gold_ball()
{
    return randNum(1, MAX_GOLD_BALL);
}
//Generate a random megaplier option (either 0 or 1)
int random_megaplier()
{
    return randNum(0, 1);
}
//Generate a random integer between min and max (inclusive)
int randNum(int min, int max)
{
    return rand() % (max - min + 1) + min;
    // by taking the remainder of dividing a random integer generated by the rand() function
    // by the range of values (max - min + 1) and adding the minimum value to shift the range
    // to start from the specified minimum value.
}

// This function generates the winning numbers for a lottery game.
void generate_winning_numbers(int* white_balls, int* gold_ball)
{

    random_white_balls(white_balls);  // Generate random white balls and store them in the array pointed to by white_balls.
    *gold_ball = random_gold_ball(); // Generate a random gold ball and store it in the variable pointed to by gold_ball.

    printf("Winning numbers: "); // Print the winning numbers.

    // Print the white balls separated by spaces.
    for(int i = 0; i < NUM_WHITE_BALLS; i++)
    {
        printf("%d ", white_balls[i]);
    }
    printf("| %d\n", *gold_ball); // Print the gold ball.
}

// Function to Generate a megaplier between (2 and 5) where it is more difficult to generate a 5 than a 2 or 3
void generate_megaplier(int* megaplier)
{
    int odds[] = {2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 5}; // Create an array of Megaplier options with their respective odds
    int index = rand() % 15; // Generate a random index between 0 and 14
    *megaplier = odds[index]; // Assign the Megaplier value at the randomly generated index to the input parameter
    printf("Megaplier: %d\n", *megaplier);
}


// Checks the tickets and sees which tickets won and lost
void check_tickets(int* winning_white_balls, int winning_gold_ball, int megaplier, char* file_name, int numTickets)
{
    // Opening the file
    FILE *lotteryF = fopen(file_name, "r");
    if(!lotteryF)
    {
        printf("Failed to open file\n"); // Print this if file doesn't open
        return;
    }

    int ticket_number, white_ball1, white_ball2, white_ball3, white_ball4, white_ball5, gold_ball, megaplier_choice; // variables to compare with tickets
    int winnings; // variable to keep track of winning amounts
    int no_meg2 = 0, no_meg4 = 0, no_meg10 = 0, no_meg200 = 0; // counter variables to keep track of winnings with no megaplier
    int meg2 = 0, meg4 = 0, meg10 = 0, meg200 = 0; // counter variables to keep track of winnings with megaplier
    int totalwinners , above400 = 0; // variables to keep track of how many tickets won
    int totalsales = numTickets * 2; // variable to keep track of total sales initialized to num of tickets by cost
    int totalpayout, temppayout = 0 , profit; // variables to keep track of total amount of payout and profit
    double averageamount; // variable to hold the averages
    int jackpot; // jackpot variable

    // This loop reads a file containing lottery tickets and compares each ticket with the winning numbers. as long as it reads 8 integers from the file else will terminate.
    while(fscanf(lotteryF, "%d %d %d %d %d %d %d %d", &ticket_number, &white_ball1, &white_ball2, &white_ball3,
                  &white_ball4, &white_ball5, &gold_ball, &megaplier_choice) == 8)
    {
        int white_balls[NUM_WHITE_BALLS] = {white_ball1, white_ball2, white_ball3, white_ball4, white_ball5};
        int num_matching_white_balls = 0;

        // loops through the generated lottery ticket and winning numbers and if any numbers are the same increments the counter to keep track
        for(int i = 0; i < NUM_WHITE_BALLS; i++)
        {
            if(white_balls[i] == winning_white_balls[i])
            {
                num_matching_white_balls++;
            }
        }

        int matches_gold_ball = (gold_ball == winning_gold_ball); // checks if the gold balls match
        int has_megaplier = (megaplier_choice == 1); // checks if megaplier choice is equal to 1 and assigns it to has_megaplier

        if(num_matching_white_balls == 5 && matches_gold_ball) // If 5 white balls match and 1 gold ball then jackpot is won
        {
            winnings = JACKPOT; // variable initialized to winning prize
        }
        else if(num_matching_white_balls == 5) // if 5 white balls are matched $ 1 million is won
        {
            winnings = 1000000; // variable initialized to winning prize
        }
        else if(num_matching_white_balls == 4 && matches_gold_ball) // if 4 whites and 1 gold then $10 thousand is won
        {
            winnings = 10000; // variable initialized to winning prize
        }
        else if(num_matching_white_balls == 4) // if 4 white balls match $500 is won
        {
            winnings = 500; // variable initialized to winning prize
        }
        else if(num_matching_white_balls == 3 && matches_gold_ball) // if 3 whites and 1 gold is matched then you win $200
        {
            winnings = 200; // variable initialized to winning prize

            // if the ticket has a megaplier increments the meg200 counter else increments the no_meg200 counter
            // to keep track of how many tickets won $200 with and without the megaplier
            if(has_megaplier)
            {
                ++meg200;
            }
            else
            {
                ++no_meg200;
            }
        }
        else if(num_matching_white_balls == 3) // if 3 matching white balls you win $10
        {
            winnings = 10; // variable initialized to winning prize

            // if the ticket has a megaplier increments the meg10 counter else increments the no_meg10 counter
            // to keep track of how many tickets won $10 with and without the megaplier
            if(has_megaplier)
            {
                ++meg10;
            }
            else
            {
                ++no_meg10;
            }
        }
        else if(num_matching_white_balls == 2 && matches_gold_ball) // if 2 matching whites and 1 gold you win $10
        {
            winnings = 10; // variable initialized to winning prize

            // if the ticket has a megaplier increments the meg10 counter else increments the no_meg10 counter
            // to keep track of how many tickets won $10 with and without the megaplier
            if(has_megaplier)
            {
                ++meg10;
            }
            else
            {
                ++no_meg10;
            }
        }
        else if(num_matching_white_balls == 1 && matches_gold_ball) // if 1 matching white and 1 gold you win $4
        {
            winnings = 4; // variable initialized to winning prize

            // if the ticket has a megaplier increments the meg4 counter else increments the no_meg4 counter
            // to keep track of how many tickets won $4 with and without the megaplier
            if(has_megaplier)
            {
                ++meg4;
            }
            else
            {
                ++no_meg4;
            }

        }
        else if(matches_gold_ball) // if matching gold you win $2
        {
            winnings = 2; // variable initialized to winning prize

            // if the ticket has a megaplier increments the meg2 counter else increments the no_meg2 counter
            // to keep track of how many tickets won $2 with and without the megaplier
            if(has_megaplier)
            {
                ++meg2;
            }
            else
            {
                ++no_meg2;
            }

        }
        else // win nothing
        {
            winnings = 0; // if the ticket does not win then it is assigned 0
        }

        // if the ticket wins and has a megaplier multiply the prize by the megaplier
        // and adds 1 to the total sales each time a ticket has a megaplier as each megaplier costs $1
        if(has_megaplier)
        {
            winnings *= megaplier;
            totalsales += 1;
        }

        // if winning is greater than $400 then it prints the ticket alongside its winnings
        if(winnings > 400)
        {
            printf("Ticket %d: %d %d %d %d %d | %d\n Megaplier: %s, \nWinnings: $%d\n",
                   ticket_number, white_ball1, white_ball2, white_ball3, white_ball4, white_ball5, gold_ball,
                   (has_megaplier ? "Yes" : "No"), winnings);
            ++above400; // tracks number of tickets above 400
            temppayout += winnings; // tracks all payouts above 400
        }

        if(winnings == JACKPOT)
        {
            jackpot = JACKPOT;
        }
    }

    // if winnings is less than $400 prints the number of tickets that won each bracket without megaplier
    if(winnings < 400)
    {
        printf("In addition without a megaplier:\n");
        printf("%d won $%d\n", no_meg2, 2);
        printf("%d won $%d\n", no_meg4, 4);
        printf("%d won $%d\n", no_meg10, 10);
        printf("%d won $%d\n", no_meg200, 200);
    }
    // if winnings is less than $400 prints the number of tickets that won each bracket without megaplier
    if(winnings < 400)
    {
        printf("In addition without a megaplier:\n");
        printf("%d won $%d\n", meg2, 2 * megaplier);
        printf("%d won $%d\n", meg4, 4 * megaplier);
        printf("%d won $%d\n", meg10, 10 * megaplier);
        printf("%d won $%d\n", meg200, 200 * megaplier);
    }

    totalwinners = no_meg2 + no_meg4 + no_meg10 + no_meg200 + meg2 + meg4 + meg10 + meg200 + above400; // adds all winners above and below $400
    totalpayout = temppayout + (no_meg2 * 2) + (no_meg4 * 4) + (no_meg10 * 10) + (no_meg200 * 200) + (meg2 * 2 * megaplier) + (meg4 * 4 * megaplier) + (meg10 * 10 * megaplier)
                    + (meg200 * 200 * megaplier); // adds the total payout for each ticket above and below $400

    printf("There are %d winners in total!\n" , totalwinners); // prints the total winners
    printf("The total sales were: $%d\n", totalsales); // prints the total sales
    printf("The total payout was: $%d\n", totalpayout); // prints the total payout

    averageamount = (double)totalpayout/numTickets;
    printf("The average amount won per ticket was: $%.2lf\n", averageamount); // prints the average amount won per ticket
    averageamount = (double)totalpayout/totalwinners;
    printf("The average amount won per winning ticket was: $%.2lf\n", averageamount); // prints the average amount won per winning ticket

    profit = totalsales - totalpayout; // calculates profit
    printf("The total profit was: $%d\n", profit); // prints the total profit

    if(jackpot == JACKPOT) // if jackpot is won it prints the cash vs annuity
    {
        cash_vs_annuity();
    }


    fclose(lotteryF); // closes file
}

// prints cash vs annuity options
void cash_vs_annuity()
{
    // variables to calculate annuity option
    int num_years = 30;
    double payment = 1500000.0;
    double interest_rate = 0.05;

    printf("If Jackpot is won:\nCash option : $100000000\n"); // prints the cas option
    printf("Annuity option :\nInitial Payment: $15000000\n");

    // calculates the annuity option for the next 30 years and prints each year with the added 5% interest
    for(int i = 1; i <= num_years; i++)
    {
        printf("Year %d: $%.2lf\n", i, payment);
        payment *= (1 + interest_rate);
    }

}
